server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 40
  jpa:
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA_NAME}
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    user: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}
    schemas: ${DATABASE_SCHEMA_NAME}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,httptrace,threaddump,scheduledtasks,metrics,mappings,beans